### ISSUE TITLE
Uploading from base64 str

### ISSUE THREAD

**Issue by nicooga** [stavro/arc#106]
I'm using master version of arc to try and upload a file directly from binary data. The use case is an API that accepts uploading images via base64 encoded strings.

However this code fails:

~~~elixir
defmodule MyApp.Image do
  use Arc.Definition
  use Arc.Ecto.Definition

  @versions [:original]
end

MyApp.Image.store(%{
  filename: "asdf.gif",
  binary: Base.decode64!("R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7")
})
~~~

```
[error] Task #PID<0.355.0> started from #PID<0.349.0> terminating
** (MatchError) no match of right hand side value: :error
    lib/arc/storage/s3.ex:67: Arc.Storage.S3.bucket/0
    lib/arc/storage/s3.ex:13: Arc.Storage.S3.put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.113666932/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
** (EXIT from #PID<0.349.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        lib/arc/storage/s3.ex:67: Arc.Storage.S3.bucket/0
        lib/arc/storage/s3.ex:13: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

It seems to be trying to upload to AWS although I didn't configure arc to use AWS.

**Comment by stavro** [comment]
arc defaults to S3, add `def __storage, do: Arc.Storage.Local` to your definition.  (I'll likely make this more visible in the future)

**Comment by nicooga** [comment]
I see, thanks for the quick answer @stavro.
