### ISSUE TITLE
SignatureDoesNotMatch error on Arc.Storage.S3

### ISSUE THREAD

**Issue by nirev** [stavro/arc#11]
I'm just starting with Elixir and Phoenix and trying to use Arc (arc_ecto, actually) to upload files to S3.

I the access keys set up in the config file, but when trying to upload I get this:

```
[error] Ranch protocol #PID<0.341.0> (:cowboy_protocol) of 
                listener X.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (ErlangError) erlang error: {:aws_error, 
              {:http_error, 403, 'Forbidden', 
              "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n
              <Error><Code>SignatureDoesNotMatch</Code>
              <Message>The request signature we calculated does not match 
              the signature you provided. Check your key and signing method.
              </Message>
              <AWSAccessKeyId>XXXX</AWSAccessKeyId>
              <StringToSign>PUT\n+NFGtaSc2qJy2E/IjvTHHA==\n\n
              Tue, 15 Sep 2015 17:45:58 GMT\nx-amz-acl:private\n
              /lukla-dev/uploads/profile.jpg</StringToSign>
              <SignatureProvided>VqTEbMI37SMKvavENE0eP+mQF2I=</SignatureProvided>
              <StringToSignBytes>50 55 54 0a 2b 4e 46 47 74 61 53 63 32 71 4a 79 32 45 
              2f 49 6a 76 54 48 48 41 3d 3d 0a 0a 54 75 65 2c 20 31 35 20 53 65 70 20 32 
              30 31 35 20 31 37 3a 34 35 3a 35 38 20 47 4d 54 0a 78 2d 61 6d 7a 2d 61 63 
              6c 3a 70 72 69 76 61 74 65 0a 2f 6c 75 6b 6c 61 2d 64 65 76 2f 75 70 6c 
              6f 61 64 73 2f 70 72 6f 66 69 6c 65 2e 6a 70 67</StringToSignBytes>
              <RequestId>A8A1CB9362F3DB59</RequestId>
              <HostId>46tQHK/X1Vl26jl+HDQr6e00/
              QqTqHxKtEy4Aq2FlFq686KYTw+0xPXzCgp3npKyVLljaufO3uE=</HostId>
              </Error>"
        }}

        (erlcloud) src/erlcloud_s3.erl:911: :erlcloud_s3.s3_request/8
        (erlcloud) src/erlcloud_s3.erl:611: :erlcloud_s3.put_object/6
        lib/arc/storage/s3.ex:9: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
```

I tried to further investigate, but I'm stuck.

The strange thing to me is that, Arc.Storage.S3/put/3 calls:
```
:erlcloud_s3.put_object(bucket, s3_key, binary, [acl: acl], erlcloud_config)
```

which looks to me as a put-object/5

yet, on the stack trace, it says :erlcloud_s3.put_object/6 was called, which expects
a list of HTTPHeaders as 5th parameter

I'm confused :confused: 

Not sure if it's a bug, or a misconfiguration on my part.

Also, my mix.lock is
```
%{"arc": {:hex, :arc, "0.1.2"},
  "arc_ecto": {:hex, :arc_ecto, "0.2.0"},
  "cowboy": {:hex, :cowboy, "1.0.3"},
  "cowlib": {:hex, :cowlib, "1.0.1"},
  "decimal": {:hex, :decimal, "1.1.0"},
  "ecto": {:hex, :ecto, "1.0.2"},
  "erlcloud": {:hex, :erlcloud, "0.9.2"},
  "fs": {:hex, :fs, "0.9.2"},
  "jsx": {:hex, :jsx, "2.1.1"},
  "lhttpc": {:hex, :lhttpc, "1.3.0"},
  "meck": {:hex, :meck, "0.8.3"},
  "mock": {:hex, :mock, "0.1.1"},
  "phoenix": {:hex, :phoenix, "1.0.2"},
  "phoenix_ecto": {:hex, :phoenix_ecto, "1.2.0"},
  "phoenix_html": {:hex, :phoenix_html, "2.2.0"},
  "phoenix_live_reload": {:hex, :phoenix_live_reload, "1.0.0"},
  "plug": {:hex, :plug, "1.0.0"},
  "poison": {:hex, :poison, "1.5.0"},
  "poolboy": {:hex, :poolboy, "1.5.1"},
  "postgrex": {:hex, :postgrex, "0.9.1"},
  "ranch": {:hex, :ranch, "1.1.0"}}
```

**Comment by stavro** [comment]
Which AWS region is the bucket located in?

**Comment by nirev** [comment]
It's in Oregon (us-west-2).

**Comment by nirev** [comment]
I just tested with a bucket in N. Virginia (us-east-1) and it fails all the same. I also don't know if this is related to timezone (??). I'm in Brazil (UTC-3).

**Comment by stavro** [comment]
I can reproduce the error when attempting to use a new bucket created in Oregon, but I can't reproduce it in US Standard.

Let me look into this more.

**Comment by nirev** [comment]
Thanks! I'll keep looking also.

**Comment by nirev** [comment]
I'm feeling pretty stupid right now, but I was able to pinpoint the issue:
there was a typo in my config file!

It was "secreat_access_key".

![](https://media.giphy.com/media/2LbsnnLhaHUnC/giphy.gif)
