### ISSUE TITLE
SSL and certificates errors for any S3 upload

### ISSUE THREAD

**Issue by alfredbaudisch** [stavro/arc#121]
I get this huge error for any S3 upload that I try. Any idea of what that could be? Thank you!

deps

``` elixir
     {:arc, "~> 0.6.0-rc3"},
     {:ex_aws, "~> 1.0.0-rc3"},
     {:hackney, "~> 1.6"},
     {:poison, "~> 2.0"},
     {:sweet_xml, "~> 0.5"}
```

applications:

``` elixir
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :fred_data, :phoenix_ecto, :postgrex, :fred_model, :ex_aws, :hackney, :poison]]
```

config (variables are in the ENV correctly):

``` elixir
config :arc,
  bucket: {:system, "S3_BUCKET"}

config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]
```

Upload (Plug.Upload):

``` elixir
Fred.Uploaders.BrandProfilePic.store({file, 1})
```
# Error

```
[error] ** State machine #PID<0.545.0> terminating
** Last message in was {:tcp, #Port<0.15908>,
 <<165, 80, 190, 45, 104, 163, 55, 0, 96, 237, 108, 3, 49, 186, 114, 199, 76,
   42, 105, 121, 192, 172, 71, 181, 5, 85, 201, 3, 217, 145, 216, 240, 19, 255,
   122, 185, 134, 112, 68, 251, 214, 219, 52, 233, 171, 146, 148, 33, ...>>}
** When State == :certify
**      Data  == [data: [{'StateData',
   {:state, :client, {#Reference<0.0.3.482>, #PID<0.534.0>}, :gen_tcp,
    :tls_connection, :tcp, :tcp_closed, :tcp_error, 's3.amazonaws.com', 443,
    #Port<0.15908>,
    {:ssl_options, :tls, [{3, 3}, {3, 2}, {3, 1}, {3, 0}], :verify_peer,
     {&:ssl_verify_hostname.verify_fun/3, [check_hostname: 's3.amazonaws.com']},
     #Function<0.117854183/1 in :hackney_connect.ssl_opts/2>, false, false,
     :undefined, 99, "", '***', "", '***', '***', '***', "", '***', :undefined,
     :undefined, '***', '***',

     [<<192, 44>>, <<192, 48>>, <<192, 36>>, <<192, 40>>, <<192, 8>>,
      <<192, 46>>, <<192, 50>>, <<192, 38>>, <<192, 42>>, <<0, 163>>,
      <<0, 106>>, <<0, 157>>, <<0, ...>>, <<...>>, ...],
     #Function<1.92387908/4 in :ssl.handle_options/2>, true, 268435456, true,
     :undefined, :undefined, false, :undefined, :undefined, :undefined,
     :undefined, true, :undefined, [], ...},
    {:socket_options, :binary, :raw, 0, 0, false}, '***', '***', '***', 36884,
    '***', 57367, :ssl_session_cache, {:ssl_crl_cache, {{49171, 53266}, []}},
    {3, 3}, false, :ecdhe_rsa, {:undefined, :undefined}, :undefined,
    {{1, 2, 840, 113549, 1, 1, 1},
     {:RSAPublicKey,
      2336709174973180170290325895133257914982471775240303673890191899557637822187699176921598611706083220593888829202067060191971732052957989742855575663375071763011381246715922945671021509
4841206836055184753491046351652384568208399197333334554354625485949013821994244854426626217946383766717620084958916568639573896625634280251135248126961353512501885364402868885624724204807768
6275584282815585894602616110239343659636208208376518997846480730966038395878833081364614481764984819344370545836647979233426096412948805214149488819813927629831732673964099539203390841750331
20756130451537931813023420728016059287928243275252817,
      65537}, :NULL}, '***', '***', '***', :undefined, '***', '***', '***',
    40981, #Reference<0.0.1.6861>, :undefined, '***', {false, :first},
    {#PID<0.534.0>, #Reference<0.0.1.6854>}, #Reference<0.0.3.483>, {[], []},
    false, :undefined, false, false, :undefined, :undefined, :undefined, ...}}]]
** Reason for termination =
** {:notsup,
 [{:crypto, :block_encrypt, 4, [file: 'crypto.erl', line: 317]},
  {:ssl_cipher, :aead_cipher, 6, [file: 'ssl_cipher.erl', line: 164]},
  {:ssl_record, :cipher_aead, 4, [file: 'ssl_record.erl', line: 406]},
  {:tls_record, :encode_plain_text, 4, [file: 'tls_record.erl', line: 144]},
  {:tls_connection, :encode_handshake, 4,
   [file: 'tls_connection.erl', line: 358]},
  {:tls_connection, :send_handshake, 2,
   [file: 'tls_connection.erl', line: 109]},
  {:ssl_connection, :client_certify_and_key_exchange, 2,

   [file: 'ssl_connection.erl', line: 1131]},
  {:tls_connection, :next_state, 4, [file: 'tls_connection.erl', line: 467]},
  {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 518]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}

[error] Task #PID<0.534.0> started from #PID<0.531.0> terminating
** (stop) exited in: :gen_fsm.sync_send_all_state_event(#PID<0.545.0>, {:start, 8000}, :infinity)
    ** (EXIT) an exception was raised:
        ** (ErlangError) erlang error: :notsup
            (crypto) crypto.erl:317: :crypto.block_encrypt/4
            (ssl) ssl_cipher.erl:164: :ssl_cipher.aead_cipher/6
            (ssl) ssl_record.erl:406: :ssl_record.cipher_aead/4
            (ssl) tls_record.erl:144: :tls_record.encode_plain_text/4
            (ssl) tls_connection.erl:358: :tls_connection.encode_handshake/4
            (ssl) tls_connection.erl:109: :tls_connection.send_handshake/2
            (ssl) ssl_connection.erl:1131: :ssl_connection.client_certify_and_key_exchange/2
            (ssl) tls_connection.erl:467: :tls_connection.next_state/4
            (stdlib) gen_fsm.erl:518: :gen_fsm.handle_msg/7
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (stdlib) gen_fsm.erl:257: :gen_fsm.sync_send_all_state_event/3      
      (stdlib) gen_fsm.erl:518: :gen_fsm.handle_msg/7
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (stdlib) gen_fsm.erl:257: :gen_fsm.sync_send_all_state_event/3
    (ssl) ssl_connection.erl:1669: :ssl_connection.sync_send_all_state_event/2
    (ssl) ssl_connection.erl:103: :ssl_connection.handshake/2
    (ssl) tls_connection.erl:82: :tls_connection.start_fsm/8
    (ssl) ssl_connection.erl:73: :ssl_connection.connect/8
    (hackney) src/hackney_connect.erl:246: :hackney_connect.do_connect/5
    (hackney) src/hackney_connect.erl:37: :hackney_connect.connect/5
    (hackney) src/hackney.erl:328: :hackney.request/5
    (ex_aws) lib/ex_aws/request/hackney.ex:20: ExAws.Request.Hackney.request/5
    (ex_aws) lib/ex_aws/request.ex:34: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/s3.ex:44: ExAws.Operation.ExAws.Operation.S3.perform/2
    (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
    (ex_aws) lib/ex_aws/s3/upload.ex:41: ExAws.S3.Upload.initialize!/2

    (ex_aws) lib/ex_aws/s3/upload.ex:83: ExAws.Operation.ExAws.S3.Upload.perform/2
    lib/arc/storage/s3.ex:53: Arc.Storage.S3.do_put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.114925626/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.531.0> (:cowboy_protocol) of listener Fred.Uploader.Endpoint.HTTP terminated
** (exit) exited in: :gen_fsm.sync_send_all_state_event(#PID<0.545.0>, {:start, 8000}, :infinity)
    ** (EXIT) an exception was raised:
        ** (ErlangError) erlang error: :notsup
            (crypto) crypto.erl:317: :crypto.block_encrypt/4
            (ssl) ssl_cipher.erl:164: :ssl_cipher.aead_cipher/6
            (ssl) ssl_record.erl:406: :ssl_record.cipher_aead/4
            (ssl) tls_record.erl:144: :tls_record.encode_plain_text/4
            (ssl) tls_connection.erl:358: :tls_connection.encode_handshake/4
            (ssl) tls_connection.erl:109: :tls_connection.send_handshake/2
            (ssl) ssl_connection.erl:1131: :ssl_connection.client_certify_and_key_exchange/2
            (ssl) tls_connection.erl:467: :tls_connection.next_state/4
            (stdlib) gen_fsm.erl:518: :gen_fsm.handle_msg/7
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
[error] ** State machine #PID<0.544.0> terminating
** Last message in was {:tcp, #Port<0.15907>,
 <<218, 145, 171, 82, 37, 106, 35, 63, 159, 83, 228, 171, 35, 78, 84, 168, 237,
   31, 160, 103, 108, 37, 231, 203, 3, 5, 216, 45, 51, 28, 123, 115, 226, 78, 8,
   157, 85, 6, 73, 43, 26, 147, 97, 238, 90, 157, 135, 117, ...>>}

** When State == :certify
**      Data  == [data: [{'StateData',
   {:state, :client, {#Reference<0.0.3.481>, #PID<0.533.0>}, :gen_tcp,
    :tls_connection, :tcp, :tcp_closed, :tcp_error, 's3.amazonaws.com', 443,
    #Port<0.15907>,
    {:ssl_options, :tls, [{3, 3}, {3, 2}, {3, 1}, {3, 0}], :verify_peer,
     {&:ssl_verify_hostname.verify_fun/3, [check_hostname: 's3.amazonaws.com']},
     #Function<0.117854183/1 in :hackney_connect.ssl_opts/2>, false, false,
     :undefined, 99, "", '***', "", '***', '***', '***', "", '***', :undefined,
     :undefined, '***', '***',
     [<<192, 44>>, <<192, 48>>, <<192, 36>>, <<192, 40>>, <<192, 8>>,
      <<192, 46>>, <<192, 50>>, <<192, 38>>, <<192, 42>>, <<0, 163>>,
      <<0, 106>>, <<0, 157>>, <<0, ...>>, <<...>>, ...],
     #Function<1.92387908/4 in :ssl.handle_options/2>, true, 268435456, true,
     :undefined, :undefined, false, :undefined, :undefined, :undefined,
     :undefined, true, :undefined, [], ...},
    {:socket_options, :binary, :raw, 0, 0, false}, '***', '***', '***', 36884,
    '***', 57367, :ssl_session_cache, {:ssl_crl_cache, {{49171, 53266}, []}},
    {3, 3}, false, :ecdhe_rsa, {:undefined, :undefined}, :undefined,
    {{1, 2, 840, 113549, 1, 1, 1},
     {:RSAPublicKey,
      2336709174973180170290325895133257914982471775240303673890191899557637822187699176921598611706083220593888829202067060191971732052957989742855575663375071763011381246715922945671021509
4841206836055184753491046351652384568208399197333334554354625485949013821994244854426626217946383766717620084958916568639573896625634280251135248126961353512501885364402868885624724204807768
6275584282815585894602616110239343659636208208376518997846480730966038395878833081364614481764984819344370545836647979233426096412948805214149488819813927629831732673964099539203390841750331
20756130451537931813023420728016059287928243275252817,
      65537}, :NULL}, '***', '***', '***', :undefined, '***', '***', '***',
    40981, #Reference<0.0.1.6859>, :undefined, '***', {false, :first},
    {#PID<0.533.0>, #Reference<0.0.1.6853>}, #Reference<0.0.1.6862>, {[], []},
    false, :undefined, false, false, :undefined, :undefined, :undefined, ...}}]]
** Reason for termination =
** {:notsup,
 [{:crypto, :block_encrypt, 4, [file: 'crypto.erl', line: 317]},
  {:ssl_cipher, :aead_cipher, 6, [file: 'ssl_cipher.erl', line: 164]},
  {:ssl_record, :cipher_aead, 4, [file: 'ssl_record.erl', line: 406]},
  {:tls_record, :encode_plain_text, 4, [file: 'tls_record.erl', line: 144]},

  {:tls_connection, :encode_handshake, 4,
   [file: 'tls_connection.erl', line: 358]},
  {:tls_connection, :send_handshake, 2,
   [file: 'tls_connection.erl', line: 109]},
  {:ssl_connection, :client_certify_and_key_exchange, 2,
   [file: 'ssl_connection.erl', line: 1131]},
  {:tls_connection, :next_state, 4, [file: 'tls_connection.erl', line: 467]},
  {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 518]},
  {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}
```

**Comment by stavro** [comment]
This looks to be an SSL issue... What OS and hosting provider is this coming from?

**Comment by stavro** [comment]
I feel like your Erlang installation is missing `:crypto`.. What happens when you start Elixir and run `:crypto.start` ?

**Comment by alfredbaudisch** [comment]
> What OS and hosting provider is this coming from?
macOS Sierra

Versions: Erlang 18, Elixir 1.3.1

> I feel like your Erlang installation is missing :crypto
```elixir
iex(1)> :crypto.start
:ok
```

I tried by adding :ssl directly to the applications. I also tried digging something from :hackney, but without success.

**Comment by stavro** [comment]
Can you try updating your machine's OpenSSL to the latest version?

**Comment by alfredbaudisch** [comment]
@stavro thanks for the suggestion. I have updated it and unfortunately the error still persists. Same message.

I'll end up just falling back to local storage in the local environment. 👍

**Comment by gemantzu** [comment]
I can confirm this exists, I have the exact same issue with @alfredbaudisch , updating macos openssl version does not help.  For the record, the openssl version I use right now is 1.0.2j (latest from homebrew).

**Comment by stavro** [comment]
I'm going to close this - As it is not an issue within `Arc` but rather an issue somewhere between hackney / crypto / OS.

Sorry I cannot be of more help!
