### ISSUE TITLE
Argument error on s3 upload

### ISSUE THREAD

**Issue by alex88** [stavro/arc#137]
I've this error when I try to save a version on S3

```
[error] Task #PID<0.639.0> started from #PID<0.633.0> terminating
** (ArgumentError) argument error
    (crypto) :crypto.hmac_nif(:sha256, ["AWS4", {:awscli, "default", 30}], "20161218")
    (crypto) crypto.erl:766: :crypto.hmac/6
    (ex_aws) lib/ex_aws/auth/signatures.ex:14: ExAws.Auth.Signatures.signing_key/3
    (ex_aws) lib/ex_aws/auth/signatures.ex:7: ExAws.Auth.Signatures.generate_signature_v4/4
    (ex_aws) lib/ex_aws/auth.ex:55: ExAws.Auth.auth_header/7
    (ex_aws) lib/ex_aws/auth.ex:18: ExAws.Auth.headers/6
    (ex_aws) lib/ex_aws/request.ex:27: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/s3.ex:44: ExAws.Operation.ExAws.Operation.S3.perform/2
    (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
    (ex_aws) lib/ex_aws/s3/upload.ex:41: ExAws.S3.Upload.initialize!/2
    (ex_aws) lib/ex_aws/s3/upload.ex:83: ExAws.Operation.ExAws.S3.Upload.perform/2
    lib/arc/storage/s3.ex:53: Arc.Storage.S3.do_put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.60039956/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```

My config is the following:

```
config :arc,
  storage: Arc.Storage.S3,
  bucket: System.get_env("AWS_S3_BUCKET") ||"project-development"

config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, "default", 30}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, {:awscli, "default", 30}, :instance_role]
```

there are no env variables set for aws, I've a profile (in the snippet I've set `default` but locally I've the profile name I want to use)

**Comment by alex88** [comment]
I think this is more an ex_aws issue, moving it there
