### ISSUE TITLE
Error while attempting to upload to s3

### ISSUE THREAD

**Issue by smithaitufe** [stavro/arc#149]
Please this is my first time using Arc and Ex_aws. I need to get this issue resolved.

This is the error I am getting

```
** (ArgumentError) argument error
        :erlang.iolist_to_binary(["https://", ["s3.us-west-2.amazonaws.com", "/", nil, "/om/files/media/5/versions/original_istock-000057793060-
large.jpg"]])
        (ex_aws) lib/ex_aws/operation/s3.ex:54: ExAws.Operation.ExAws.Operation.S3.url/3
        (ex_aws) lib/ex_aws/operation/s3.ex:34: ExAws.Operation.ExAws.Operation.S3.perform/2
        (ex_aws) lib/ex_aws.ex:41: ExAws.request!/2
        (ex_aws) lib/ex_aws/s3/upload.ex:41: ExAws.S3.Upload.initialize!/2
        (ex_aws) lib/ex_aws/s3/upload.ex:83: ExAws.Operation.ExAws.S3.Upload.perform/2
        lib/arc/storage/s3.ex:57: Arc.Storage.S3.do_put/3
        (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
Here is my model following a guide online

```
defmodule Store.Image do
  use Store.Web, :model

  schema "images" do
    field :name, :string
    field :upload, :any, virtual: true
    
    timestamps()
  end

  @required_fields [:upload]
  @optional_fields []

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
  end
  def attachment_changeset(struct, params \\ %{}) do
    struct
    |> changeset(params)
    |> put_name()
    |> cast(params, [:name])
  end
  def put_name(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{upload: %Plug.Upload{content_type: "image/" <> _, filename: name}}} ->
        put_change(changeset, :name, name)
      _ -> changeset
      
    end
  end
  def store(%Plug.Upload{} = upload, image) do
    Store.Uploader.store({upload, image})
  end
  def url(image, version) do
    Store.Uploader.url({image.name, image}, version)
  end

end

```

And here is my uploader.ex

```
defmodule Store.Uploader do
  use Arc.Definition

  # Include ecto support (requires package arc_ecto installed):
  # use Arc.Ecto.Definition
  @acl :public_read
  @height %{show: 315, thumb: 40, slide: 250}
  @versions [:original, :thumb, :show, :slide]

  # Whitelist file extensions:
  def validate({file, _}) do
    ~w(.jpg .jpeg .gif .png) |> Enum.member?(Path.extname(file.file_name))
  end

  # Define a thumbnail transformation:
  def transform(:thumb, _) do
    {:convert, "-strip -thumbnail x#{@height[:thumb]}^ -gravity center -extent x#{@height[:thumb]} -format png", :png}
  end
  def transform(:show, _) do
    {:convert, "-strip -resize x#{@height[:show]}^ -gravity center -extent x#{@height[:show]} -format png", :png}
  end
  def transform(:slide, _) do
    {:convert, "-strip -resize x#{@height[:slide]}^ -gravity center -extent x#{@height[:slide]} -format png", :png}
  end
  

  # Override the persisted filenames:
  def filename(version, {file, _}) do
    Path.rootname("#{version}_#{file.file_name}")
  end
  # using local storage
  # def __storage, do: Arc.Storage.Local
  
  # Override the storage directory:
  def storage_dir(version, {_, image}) do
    # "uploads/user/avatars/#{scope.id}"
    # "om/files/media/#{image.id}/versions/#{image.id}/#{version}"
    "om/files/media/#{image.id}/versions"
  end

  # Provide a default URL if there hasn't been a file uploaded
  # def default_url(version, scope) do
  #   "/images/avatars/default_#{version}.png"
  # end

  # Specify custom headers for s3 objects
  # Available options are [:cache_control, :content_disposition,
  #    :content_encoding, :content_length, :content_type,
  #    :expect, :expires, :storage_class, :website_redirect_location]
  #
  # def s3_object_headers(version, {file, scope}) do
  #   [content_type: Plug.MIME.path(file.file_name)]
  # end
end
```

I am sending the image from a frontend using Aurelia and here is the image_controller that responds to the upload endpoint

```
def create(conn, %{"image" => image_params}) do
        params = %{upload: image_params}
        changeset = Image.attachment_changeset(%Image{}, params)        

        case Repo.insert(changeset) do
            {:ok, image} ->
                Image.store(image_params, image)

                conn            
                |> put_status(:created)
                |> put_resp_header("location", v1_image_path(conn, :show, image))
                |> render("show.json", image: image)
            {:error, changeset} ->
                conn
                |> put_status(:unprocessable_entity)
                |> render(Store.ChangesetView, "error.json", changeset: changeset)
        end
    end
```
Here is my config.ex for arc and ex_aws

```
config :arc,
  storage: Arc.Storage.S3,
  bucket: {:system, "downloadsz"},
  virtual_host: true

config :ex_aws,
 access_key_id: "*******************************",
 secret_access_key: "*********************",
 region: "us-west-2",
 host: "s3.us-west-2.amazonaws.com",
 s3: [
 scheme: "https://",
 host: "s3.us-west-2.amazonaws.com",
 region: "us-west-2"
 ]
```
This may not be an issue though

**Comment by smithaitufe** [comment]
I think the previous error has been resolved after I changed the config :arc in config.ex to 
```
config :arc,
  storage: Arc.Storage.S3,
  bucket: "downloadsz"
```
I am currently having this error

```
[error] %ExAws.Error{message: "ExAws Request Error!\n\n{:error, {:http_error, 403, %{body: \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\
\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>C6399AA9F4070B65</RequestId><HostId>XzOEomu09HVPDSXANE5HZgkxLE042eF
NrPaKl5vLtVILy069ffJT6VqtAnlQHQKYy244HTbJKCU=</HostId></Error>\", headers: [{\"x-amz-request-id\", \"C6399AA9F4070B65\"}, {\"x-amz-id-2\", \"XzO
Eomu09HVPDSXANE5HZgkxLE042eFNrPaKl5vLtVILy069ffJT6VqtAnlQHQKYy244HTbJKCU=\"}, {\"Content-Type\", \"application/xml\"}, {\"Transfer-Encoding\", \
"chunked\"}, {\"Date\", \"Mon, 16 Jan 2017 18:43:42 GMT\"}, {\"Server\", \"AmazonS3\"}], status_code: 403}}}\n"}
[error] ExAws Request Error!
```

I think this is policy issue. But I have defined a policy like this in the bucket

```
{
	"Version": "2012-10-17",
	"Id": "PublicCanGetProducts",
	"Statement": [
		{
			"Sid": "readonly policy",
			"Effect": "Allow",
			"Principal": {
				"AWS": "*"
			},
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::downloadsz/om/files/media/*"
		},
{
                "Sid": "upload files",
                "Effect": "Allow",
                "Principal": {
                    "AWS":"arn:aws:iam::981988496861:user/Smith"
                },
                "Action":"s3:PutObject",
                "Resource":"arn:aws:s3:::downloadsz/om/files/media/*"
            }

	]
}
```

What can be cause of this error?

**Comment by benwilson512** [comment]
In the first case you were missing the access keys from your config.

In your new config, it seems that you have `{:system, "downloadz"}` as the bucket which means I assume that it's going to look for an environment variable named "downloadz" in order to get the actual bucket name. Is that correct?

**Comment by smithaitufe** [comment]
@benwilson512 

Thanks for reaching out

I have changed it to something  like this

```
# Configure Arc and ex_aws for uploads
config :arc,
  storage: Arc.Storage.S3,
  bucket: "downloadsz"

config :ex_aws,
 access_key_id: [{:system, "*************"}, :instance_role],
 secret_access_key: [{:system, "********"}, :instance_role],
 region: "us-west-2",
 host: "s3.amazonaws.com",
 s3: [
 scheme: "https://",
 host: "s3.us-west-2.amazonaws.com",
 region: "us-west-2"
 ]
```

*********** is replaced with my access key and secret respectively

downloadsz is the name of the bucket

**Comment by benwilson512** [comment]
You seem to be a bit unclear about what `{:system` does. The purpose of the `{:system` tuple is that you have`{:system, "NAME_OF_ENVIRONMENT_VARIABLE"}`. The idea is that you have an environment variable defined with the name `NAME_OF_ENVIRONMENT_VARIABLE` and a value that  has whatever value you want to be kept secret.

If you're going to just hard code the value in your config you don't need to use it at all. You'd just do
```
config :arc,
  storage: Arc.Storage.S3,
  bucket: "downloadsz"

config :ex_aws,
 access_key_id: "*************",
 secret_access_key: "********",
 region: "us-west-2",
 host: "s3.amazonaws.com",
 s3: [
 scheme: "https://",
 host: "s3.us-west-2.amazonaws.com",
 region: "us-west-2"
 ]
```

However I don't recommend this. The best route is to just define environment variables and use `{:system,` tuples.

**Comment by smithaitufe** [comment]
@benwilson512 My dear, thanks so much. 
I understand the use of system better now. I will change to using it.
I noticed something else was wrong with my config. I changed the host from `s3.us-west-2.amazonaws.com` to `s3-us-west-2.amazonaws.com`

See the changes below

```
# Configure Arc and ex_aws for uploads
config :arc,
  storage: Arc.Storage.S3,
  bucket: "downloadsz"

config :ex_aws,
 access_key_id: "***************************",
 secret_access_key: "************************",
 region: "us-west-2",
 host: "s3-us-west-2.amazonaws.com",
 s3: [
 scheme: "https://",
 host: "s3-us-west-2.amazonaws.com",
 region: "us-west-2"
 ]
```

It has worked.
