### ISSUE TITLE
Error after uploading to S3

### ISSUE THREAD

**Issue by hiaw** [stavro/arc#200]
I managed to get arc working fine in development. But when i tried to use it in production. I got this. I'm not sure how to debug this. Help?

```
Task #PID<0.2405.0> started from #PID<0.2404.0> terminating
** (KeyError) key :src not found in: %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<InitiateMultipartUploadResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Bucket>smish-prod-au</Bucket><Key>uploads/item_images/SXRlbTo2_93289682_original.jpg</Key><UploadId>xt_U.ekkvlrQAPUt3uMD3OXb__QdGVHBkPRDIKJveahgoUtBu5hSxlh0miq_RcVj5fcfNZkeMfjf7kJbNGn_TcKaw7nqgE5uoM2d1wxijDE-</UploadId></InitiateMultipartUploadResult>", headers: [{"x-amz-id-2", "zEPP4PTnCmvxQFvkMerml0qFbfc8UqrTePJamQkbda3areMVhlTR9UwSsvR7k54xvn7Pe2Mfwh4="}, {"x-amz-request-id", "E9C4E0A22E016941"}, {"Date", "Sat, 17 Jun 2017 08:52:35 GMT"}, {"Transfer-Encoding", "chunked"}, {"Server", "AmazonS3"}], status_code: 200}
    (ex_aws) lib/ex_aws/s3/upload.ex:83: ExAws.Operation.ExAws.S3.Upload.perform/2
    (arc) lib/arc/storage/s3.ex:57: Arc.Storage.S3.do_put/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.52315234/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```

**Comment by hiaw** [comment]
I think I fixed it by adding `:sweet_xml` to the `applications` list
