### ISSUE TITLE
Getting "is invalid"

### ISSUE THREAD

**Issue by Aleksion** [stavro/arc#217]
Hi, 

I wasn't sure which of the arc repositories to post this in, so I've created a bit of duplicates. 
I created another issue on arc_gcs (https://github.com/martide/arc_gcs/issues/9).

 I'm currently getting an file: "is invalid" whenever I try to upload a file. 

```
    ** (Protocol.UndefinedError) protocol Enumerable not implemented for #Ecto.Changeset<action: :insert, changes: %{store_id: "3010fc45-1736-4010-8cf8-d29f33d72182"}, errors: [file: {"is invalid", [type: Bounce.ImageFile.Type, validation: :cast]}], data: #Bounce.Partners.StoreImage<>, valid?: false>. This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Stream, Timex.Interval
        (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir) /private/tmp/elixir-20170801-32483-1rf8an1/elixir-1.5.1/lib/elixir/lib/enum.ex:116: Enumerable.reduce/3
        (elixir) lib/enum.ex:1823: Enum.reverse/1
        (elixir) lib/enum.ex:2581: Enum.to_list/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:258: Absinthe.Phase.Document.Execution.Resolution.split_error_value/1
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:248: Absinthe.Phase.Document.Execution.Resolution.put_result_error_value/6
        (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:243: Absinthe.Phase.Document.Execution.Resolution.build_error_result/7
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:150: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:87: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:57: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:25: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
        (absinthe) lib/absinthe/pipeline.ex:248: Absinthe.Pipeline.run_phase/3
        (absinthe_plug) lib/absinthe/plug.ex:274: Absinthe.Plug.run_query/3
        (absinthe_plug) lib/absinthe/plug.ex:202: Absinthe.Plug.execute/2
        (absinthe_plug) lib/absinthe/plug.ex:155: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:161: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (bounce) lib/bounce_web/endpoint.ex:1: BounceWeb.Endpoint.plug_builder_call/2
        (bounce) lib/plug/debugger.ex:99: BounceWeb.Endpoint."call (overridable 3)"/2
```

and this is the data I'm trying to add:

```
%{file: %Plug.Upload{content_type: "image/png", filename: "Ad image 3.png",
   path: "/var/folders/hb/khsycbjd2ss661zpfd05hyrc0000gn/T//plug-1505/multipart-1505513892-718525603331182-6"},
  store_id: "3010fc45-1736-4010-8cf8-d29f33d72182"}
```

I'm using

Phoenix 1.3
Absinthe
arc
arc_ecto
arc_gcs

**Comment by Aleksion** [comment]
The issue was my credentials for google cloud. Closing this and continuing on arc_gcs
