### ISSUE TITLE
Problems using Arc (thumbnail) with phoenix 1.3

### ISSUE THREAD

**Issue by dielume** [stavro/arc#233]
i can uploads images with the Arc module but when i try to use transform(:thumb, _) for resize image . I have the following isue

```
%{"image" => %Plug.Upload{content_type: "image/png", filename: "perfil.png",
   path: "/var/folders/z2/51h_j79s4l36s68fyn849c5c0000gn/T//plug-1516/multipart-1516065376-206279272775698-4"}}
[error] Task #PID<0.472.0> started from #PID<0.467.0> terminating
** (Arc.MissingExecutableError) Cannot locate executable: convert

    (arc) lib/arc/transformations/convert.ex:22: Arc.Transformations.Convert.ensure_executable_exists!/1
    (arc) lib/arc/transformations/convert.ex:7: Arc.Transformations.Convert.apply/3
    (arc) lib/arc/actions/store.ex:57: Arc.Actions.Store.put_version/3
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.46555105/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.467.0> (:cowboy_protocol) of listener ImageerWeb.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (Arc.MissingExecutableError) Cannot locate executable: convert

        (arc) lib/arc/transformations/convert.ex:22: Arc.Transformations.Convert.ensure_executable_exists!/1
        (arc) lib/arc/transformations/convert.ex:7: Arc.Transformations.Convert.apply/3
        (arc) lib/arc/actions/store.ex:57: Arc.Actions.Store.put_version/3
        (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

```

my Arc module:

```
defmodule ImageerWeb.ImageUploader do
  use Arc.Definition
  use Arc.Ecto.Definition

  @versions [:original, :thumb]

  def __storage do
    Arc.Storage.Local
  end
 
  @versions [:original, :thumb]

  def validate({file, _}) do
    ~w(.jpg .jpeg .gif .png) |> Enum.member?(Path.extname(file.file_name))
  end

  def transform(:thumb, _) do
    {:convert, "-strip -thumbnail 100x100^ -gravity center -extent 100x100"}
  end
end
```

**Comment by pedep** [comment]
Your problem lies in
`** (Arc.MissingExecutableError) Cannot locate executable: convert`

You have to install ImageMagick, which provides the convert executable.
Assuming your distro, you might do something like `sudo apt-get install imagemagick` on ubuntu.

**Comment by dielume** [comment]
Many thanks for the early answer,

I use Mac, all was solve with

`brew install imagemagick`

thanks a lot,  

I will close the issue

**Comment by pedep** [comment]
Cheers :smile:
