### ISSUE TITLE
Can't upload from Safari

### ISSUE THREAD

**Issue by Yamilquery** [stavro/arc#253]
I can't upload images from Safari.

```
defmodule NuuGroup.ArcUploaders.Concept do
  use Arc.Definition
  use Arc.Ecto.Definition

  @versions [:original, :thumb100, :thumb200, :thumb400, :thumb600, :thumb800, :thumb1200]

  def validate({file, _}) do
    ~w(.jpg .jpeg .png) |> Enum.member?(Path.extname(file.file_name))
  end

  def transform(:thumb100, _), do: {:convert, "-resize 100> -format png", :png}
  def transform(:thumb200, _), do: {:convert, "-resize 200> -format png", :png}
  def transform(:thumb400, _), do: {:convert, "-resize 400> -format png", :png}
  def transform(:thumb600, _), do: {:convert, "-resize 600> -format png", :png}
  def transform(:thumb800, _), do: {:convert, "-resize 800> -format png", :png}
  def transform(:thumb1200, _), do: {:convert, "-resize 1200> -format png", :png}

  def filename(version, {file, scope}) do
    "c_#{version}_#{scope.id}"
  end

  def storage_dir(version, {file, scope}) do
    "uploads/images/concepts/#{scope.concept_id}"
  end

end
```

**Chrome:**
<img width="771" alt="screen shot 2018-05-11 at 13 10 44" src="https://user-images.githubusercontent.com/6020065/39939757-df899e24-551c-11e8-9ab2-274df90948e8.png">

_Safari:_
<img width="774" alt="screen shot 2018-05-11 at 13 10 35" src="https://user-images.githubusercontent.com/6020065/39939764-e6c5b452-551c-11e8-8a78-362c31ba9e10.png">

**Error obtained:**

```
[error] #PID<0.4974.0> running NuuGroup.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api
** (exit) an exception was raised:
    ** (ErlangError) Erlang error: {:nocatch, {:error, #Ecto.Changeset<action: :update, changes: %{}, errors: [image_url: {"is invalid", [type: NuuGroup.ArcUploaders.Concept.Type, validation: :cast]}], data: #Yellowbox.Concepts.ConceptImage<>, valid?: false>}}
        (yellowbox) lib/yellowbox/concepts/graphql/resolver.ex:106: anonymous fn/2 in Yellowbox.Concepts.Graphql.Resolver.create_concept/1
        (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
        (db_connection) lib/db_connection.ex:1374: DBConnection.transaction_nested/2
        (db_connection) lib/db_connection.ex:1234: DBConnection.transaction_meter/3
        (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
        (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
        (yellowbox) lib/yellowbox/concepts/graphql/resolver.ex:178: Yellowbox.Concepts.Graphql.Resolver.create_concept/1
        (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto) lib/ecto/multi.ex:411: anonymous fn/5 in Ecto.Multi.apply_operations/5
        (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
        (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
        (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
        (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
        (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
        (yellowbox) lib/yellowbox/concepts/graphql/resolver.ex:696: Yellowbox.Concepts.Graphql.Resolver.upload_concept_to_library/3
        (absinthe) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
        (absinthe) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
```

### Environment

* Elixir version (elixir -v): **Elixir 1.6.4 (compiled with OTP 20)**
* Arc version (mix deps): **0.8.0**
* Arc dependencies when applicable (mix deps): **0.7.0**
* Operating system: Mac OS X Sierra 10.13.1

### Expected behavior

Achieve upload an image from Safari

### Actual behavior

The images are uploaded in white from Safari and if I apply a transformation in arc configuration file, it sends an error that says, "is invalid".

**Comment by stavro** [comment]
If you can share some of your controller code I can help debug, there isn't enough information here, but my guess is that you're not referencing the actual upload binary from Plug correctly.
