### ISSUE TITLE
error in lib/arc/storage/s3.ex:69: Arc.Storage.S3.bucket/0

### ISSUE THREAD

**Issue by AndwareSsj** [stavro/arc#59]
i get this error:
```
[error] Task #PID<0.487.0> started from #PID<0.463.0> terminating
** (MatchError) no match of right hand side value: :error
    lib/arc/storage/s3.ex:69: Arc.Storage.S3.bucket/0
    lib/arc/storage/s3.ex:14: Arc.Storage.S3.put/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<4.60738616/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
```

but i didn't use s3 storage.

avatar params:
```
%{avatar: %Plug.Upload{content_type: "image/png", filename: "Klogo副本.png", 
   path: "/var/folders/pn/jhz7bfx944b0ftdxrxtlsv7h0000gn/T//plug-1459/multipart-849582-337479-2"},
  id: 12}
```

user params:
```
%ChinaPhoneix.User{__meta__: #Ecto.Schema.Metadata<:loaded>, admin: false,
 age: nil, avatar: nil, comments: [], email: "397483056@qq.com", id: 12,
 inserted_at: #Ecto.DateTime<2016-04-05T08:54:52Z>, name: "ssj4429108",
 password: nil, password_confirmation: nil,
 password_digest: "$2b$12$FOGrltWbsFXEMu24RXf1VOriDQaB3fXPS3WfWi5NzHflvDOYma/kC",
 posts: [], score: 1, updated_at: #Ecto.DateTime<2016-04-05T09:00:50Z>}
```

error in 
```
          changeset = User.update_changeset(user, params)

```

**Comment by stavro** [comment]
The default storage option is S3.  If you would like to persist things locally, you'll need to provide an alternative storage module in your definition:


```
def __storage, do: Arc.Storage.Local
```

If you do want to use S3, you will need to properly configure it:

```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role]
```

**Comment by AndwareSsj** [comment]
I think like this:
```
defp deps do
  [
    arc: "~> 0.5.1",
    ex_aws: "~> 0.4.10", # Required if using Amazon S3
    httpoison: "~> 0.7"  # Required if using Amazon S3
    poison: "~> 1.2"     # Required if using Amazon S3
  ]
end
```
S3 is optional,so Storage.local is default

**Comment by stavro** [comment]
S3 is the default.  I should perhaps change this, but you'll need to explicitly set the storage to `local` for now if you want to use local.

https://github.com/stavro/arc/blob/master/lib/arc/definition/storage.ex#L11

**Comment by grounded-warrior** [comment]
I get this in my test only when trying to use FakeS3, has anyone experienced that? All other envs work fine
