### ISSUE TITLE
Erlang list_to_integer error while uploading

### ISSUE THREAD

**Issue by aghosh47** [stavro/arc#79]
Hi, I am using arc and arc_ecto.

I have included the bucket name like 
```
config :arc,
  bucket: "arn:aws:s3:::bucket-name/"
```

And I have ex_aws: configuration

```
config :ex_aws,
  debug_requests: true,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}],
  region: "us-west-2"

config :ex_aws, :httpoison_opts,
    recv_timeout: 60_000,
    hackney: [recv_timeout: 60_000, pool: false]
```

Now when I try to upload a file, with phoenix, I have an error:

```
[debug] Processing by Expense.TransactionController.create/2
  Parameters: %{"_csrf_token" => "MWtWVml4EAADHE0mB2V+AEoQEQJz7oN3K68xg9QQ==", "_utf8" => "✓", "account_id" => "1", "transaction" => %{"amount" => "1234", "date" => %{"day" => "1", "month" => "6", "year" => "2016"}, "description" => "", "receipt" => %Plug.Upload{content_type: "image/png", filename: "Screenshot from 2016-05-26 16:17:21.png", path: "/tmp/plug-1465/multipart-534432-578580-2"}}}
  Pipelines: [:browser]
[debug] SELECT u0.`id`, u0.`name`, u0.`email`, u0.`encrypted_password`, u0.`verified_at`, u0.`verified`, u0.`role`, u0.`inserted_at`, u0.`updated_at` FROM `users` AS u0 WHERE (u0.`id` = ?) [1] OK query=0.7ms
[debug] SELECT a0.`id`, a0.`name`, a0.`activated`, a0.`user_id`, a0.`inserted_at`, a0.`updated_at` FROM `accounts` AS a0 WHERE (a0.`id` = ?) [1] OK query=0.9ms queue=0.1ms
[debug] SELECT t0.`id`, t0.`amount`, t0.`date`, t0.`description`, t0.`approved_at`, t0.`deleted_at`, t0.`receipt`, t0.`approved_by`, t0.`deleted_by`, t0.`user_id`, t0.`account_id`, t0.`inserted_at`, t0.`updated_at` FROM `transactions` AS t0 WHERE (t0.`account_id` = ?) [1] OK query=1.9ms queue=0.1ms
[debug] SELECT a0.`id`, a0.`name`, a0.`activated`, a0.`user_id`, a0.`inserted_at`, a0.`updated_at` FROM `accounts` AS a0 WHERE (a0.`id` = ?) [1] OK query=1.8ms queue=0.1ms
[debug] Request URL: "https://arn:aws:s3:::memento-is-dev/.s3-us-west-2.amazonaws.com/uploads/Screenshot from 2016-05-26 16:17:21.png"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC Credential=accesskey/20160610/us-west-2/s3/aws4_request,SignedHeaders=content-length;host;x-amz-acl;x-amz-content-sha256;x-amz-date,Signature=9e9ced01075"}, {"host", "arn"}, {"x-amz-date", "20160610T045352Z"}, {"content-length", 75189}, {"x-amz-acl", "private"}, {"x-amz-content-sha256", "2d969d852e270a4c0aa2a73"}]
[debug] Request BODY: <<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 5, 86, 0, 0, 3, 0, 8, 6, 0, 0, 0, 207, 62, 60, 194, 0, 0, 0, 4, 115, 66, 73, 84, 8, 8, 8, 8, 124, 8, 100, 136, 0, ...>>
[error] Task #PID<0.734.0> started from #PID<0.721.0> terminating
** (ArgumentError) argument error
    :erlang.list_to_integer('aws:s3:::test-bucket/')
    (hackney) src/hackney_url.erl:196: :hackney_url.parse_netloc/2
    (hackney) src/hackney.erl:341: :hackney.request/5
    (httpoison) lib/httpoison/base.ex:396: HTTPoison.Base.request/9
    (ex_aws) lib/ex_aws/request/httpoison.ex:35: ExAws.Request.HTTPoison.request/4
    (ex_aws) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
    lib/arc/storage/s3.ex:14: Arc.Storage.S3.put/3
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<4.37961548/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.721.0> (:cowboy_protocol) of listener Expense.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.list_to_integer('aws:s3:::test-bucket')
        (hackney) src/hackney_url.erl:196: :hackney_url.parse_netloc/2
        (hackney) src/hackney.erl:341: :hackney.request/5
        (httpoison) lib/httpoison/base.ex:396: HTTPoison.Base.request/9
        (ex_aws) lib/ex_aws/request/httpoison.ex:35: ExAws.Request.HTTPoison.request/4
        (ex_aws) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
        lib/arc/storage/s3.ex:14: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by stavro** [comment]
Because you've set the bucket name to "arn:aws:s3:::bucket-name/", and the bucket name is a subdomain of the final URL, the URI library is interpreting everything after the first colon as the PORT, which it then errors out converting to an integer.

Instead, just use "bucket-name" as the bucket name. Do not use the aws resource identifier.

**Comment by aghosh47** [comment]
thanks

**Comment by aghosh47** [comment]
@stavro when I try to access an image like `MyApp.Avatar.url({ user.photo, user}, :thumb, signed: true)`

it throws this error:

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
<AWSAccessKeyId>ACCESSID</AWSAccessKeyId>
<StringToSign>
AWS4-HMAC-SHA256 20160613T132235Z 20160613/us-east-1/s3/aws4_request 3119114
</StringToSign>
<SignatureProvided>
f1e2764695
</SignatureProvided>
<StringToSignBytes>
 stuff
</StringToSignBytes>
<CanonicalRequest>
GET /memento-is-dev/uploads/Screenshot%20from%202016-05-24%2014%3A43%3A13.png X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ACCESS%2F20160613%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160613T131355Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&v=63633027268 host:s3.amazonaws.com host UNSIGNED-PAYLOAD
</CanonicalRequest>
<CanonicalRequestBytes>
stuff
</CanonicalRequestBytes>
<HostId>
fjO3c4Y=
</HostId>
</Error>
```

**Comment by aghosh47** [comment]
I had checked that if my aws access key had trailing spaces or not .. but there are none.
