### ISSUE TITLE
Local file is processed and uploaded to S3 but nothing is stored in database

### ISSUE THREAD

**Issue by ospaarmann** [stavro/arc#88]
I'm following the examples in the Readme closely but I cannot get it to work. I think something is wrong here.

I'm using elixirs Arc with Ecto and Amazon S3 to store files that I have previously downloaded. Everything seems to work, they end up on S3. But nothing is stored in my database. So if I try to generate an URL I always just get the default image back.

This is how I store a file:

```
iex > user = Repo.get(User, 3)
iex > Avatar.store({"/tmp/my_file.png", user})
{:ok, "my_file.png"}
iex > user.avatar
nil
```

But the `user.avatar` field is still nil.

My user module:
```

defmodule MyApp.User do
  use MyApp.Web, :model
  use Arc.Ecto.Schema

  alias MyApp.Repo

  schema "users" do
    field :name, :string
    field :email, :string
    field :avatar, MyApp.Avatar.Type    
    embeds_many :billing_emails, MyApp.BillingEmail
    embeds_many :addresses, MyApp.Address
    timestamps
  end

  @required_fields ~w(name email)
  @optional_fields ~w(avatar)

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> cast_embed(:billing_emails)
    |> cast_embed(:addresses)
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
    |> cast_attachments(params, [:avatar])
  end

end
```

The Avatar uploader:

```
defmodule MyApp.Avatar do
  use Arc.Definition

  # Include ecto support (requires package arc_ecto installed):
  use Arc.Ecto.Definition

  @acl :public_read

  # To add a thumbnail version:
  @versions [:original, :thumb]

  # Whitelist file extensions:
  def validate({file, _}) do
    ~w(.jpg .jpeg .gif .png) |> Enum.member?(Path.extname(file.file_name))
  end

  # Define a thumbnail transformation:
  def transform(:thumb, _) do
    {:convert, "-strip -thumbnail 250x250^ -gravity center -extent 250x250 -format png", :png}
  end

  def transform(:original, _) do
    {:convert, "-format png", :png}
  end

  def filename(version,  {file, scope}), do: "#{version}-#{file.file_name}"

  # Override the storage directory:
  def storage_dir(version, {file, scope}) do
    "uploads/user/avatars/#{scope.id}"
  end

  # Provide a default URL if there hasn't been a file uploaded
  def default_url(version, scope) do
    "/images/avatars/default_#{version}.png"
  end

end
```

**Comment by stavro** [comment]
nowhere is the value of the avatar filename being casted or persisted to the model.  Take a look at the other repository mentioned in the Readme `arc_ecto`

**Comment by ospaarmann** [comment]
But I have it in the user module. I don't see the difference to the examples in the readme:

```
def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> cast_embed(:billing_emails)
    |> cast_embed(:addresses)
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
    |> cast_attachments(params, [:avatar])
  end
```

Sorry if this is a stupid question but it just isn't clear from the examples what is missing.

**Comment by stavro** [comment]
(on my phone so pardon the formatting)

I'm your controller where you save the upload:

```
iex > user = Repo.get(User, 3)
iex > Avatar.store({"/tmp/my_file.png", user})
{:ok, "my_file.png"}
```

you should not need to call `store` directly.  you should be able to pass the params directly do `User.changeset`, followed by a `Repo.update`.

**Comment by stavro** [comment]
i.e. `Repo.get(User, 1) |> User.changeset(params) |> Repo.update()`

**Comment by ospaarmann** [comment]
No worries. Thank you for your help! When I try this:

```
params = %{avatar: "/tmp/my_file.png"}
Repo.get(User, 1) |> User.changeset(params) |> Repo.update()
```

I get this error:

```
[error] Task #PID<0.463.0> started from #PID<0.451.0> terminating
** (UndefinedFunctionError) function nil.id/0 is undefined (module nil is not available)
    nil.id()
    (my_app) MyApp.Avatar.storage_dir/2
    lib/arc/storage/s3.ex:5: Arc.Storage.S3.put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.82074396/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
** (EXIT from #PID<0.451.0>) an exception was raised:
    ** (UndefinedFunctionError) function nil.id/0 is undefined or private
        nil.id()
        (my_app) MyApp.Avatar.storage_dir/2
        lib/arc/storage/s3.ex:5: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by stavro** [comment]
Remove avatar from `optional_fields`. it should not be triggered through both cast and cast_attachments.

**Comment by ospaarmann** [comment]
That did the trick. It would be great to mention this and the fact that you should use changesets in the Readme. Right now it can look (for the inexperienced user) like Avatar.store is all you have to do. Thanks again!

**Comment by ckgagan** [comment]
Hey
How does it work with nested form. Like product has many images

Here are my changeset for product and images model

product model
```
defmodule MyApp.Product do
  use MyApp.Web, :model

  schema "products" do
    field :name, :string
    field :brand, :string
    field :color, :string
    field :description, :string
    field :buying_price, :float
    field :selling_price, :float
    field :category, :string
    field :featured, :boolean, default: false
    field :image_url, :string
    field :slug, :string
    field :best_seller, :boolean, default: false
    field :new_arrival, :boolean, default: false
    field :discounted, :boolean, default: false
    field :discounted_price, :float
    field :must_have, :boolean, default: false
    has_many :images, MyApp.Image

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :brand, :color, :description, :buying_price, :selling_price, :category, :featured, :image_url, :slug, :best_seller, :new_arrival, :discounted, :discounted_price, :must_have])
    |> validate_required([:name, :brand, :color, :description, :buying_price, :selling_price, :category])
    |> cast_assoc(:images)
  end

end

```

image model 

```
defmodule MyApp.Image do
  use MyApp.Web, :model
  use Arc.Ecto.Schema

  schema "images" do
    field :url, MyApp.ImageUploader.Type
    field :delete, :boolean, virtual: true
    belongs_to :product, MyApp.Product

    timestamps()
  end
  
  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:url])
    |> set_delete_action()
    |> cast_attachments(params, [:url])
  end

  def set_delete_action(changeset) do
    if get_change(changeset, :delete) do
      %{changeset | delete: :action}
    else
      changeset
    end
  end
end
```

And the product controller create action
```
  def create(conn, %{"product" => product_params}) do
    changeset = Product.changeset(%Product{}, product_params)

    case Repo.insert(changeset) do
      {:ok, _product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: product_path(conn, :index))
      {:error, changeset} ->

        render(conn, "new.html", changeset: changeset)
    end
  end
```

I got the similar error as @ospaarmann got

Post params for create action and error
```
[info] POST /admin/products
[debug] Processing by Briggstreet.Admin.ProductController.create/2
  Parameters: %{"_csrf_token" => "AQA2bk48ABRTHGMxORFSQC44JTZ7EAAAWHpEvEIcdtVGPVj0WnNpLA==", "_utf8" => "✓", "product" => %{"best_seller" => "true", "brand" => "Gaga", "buying_price" => "25", "category" => "Jeans", "color" => "Black", "description" => "dg fggg dg", "discounted" => "false", "discounted_price" => "", "featured" => "true", "images" => %{"0" => %{"url" => %Plug.Upload{content_type: "image/jpeg", filename: "lee men 41.jpg", path: "/tmp/plug-1481/multipart-860461-78405-2"}}, "1481859504137" => %{"url" => [%Plug.Upload{content_type: "image/jpeg", filename: "lee men 42.jpg", path: "/tmp/plug-1481/multipart-860461-79151-2"}]}}, "must_have" => "false", "name" => "Gaga Jeans v1", "new_arrival" => "false", "selling_price" => "40"}}
  Pipelines: [:browser]
[error] Task #PID<0.470.0> started from #PID<0.442.0> terminating
** (UndefinedFunctionError) function nil.id/0 is undefined (module nil is not available)
    nil.id()
    (briggstreet) Briggstreet.ImageUploader.storage_dir/2
    lib/arc/storage/s3.ex:6: Arc.Storage.S3.put/3
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<0.60039956/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.442.0> (:cowboy_protocol) of listener Briggstreet.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.id/0 is undefined or private
        nil.id()
        (briggstreet) Briggstreet.ImageUploader.storage_dir/2
        lib/arc/storage/s3.ex:6: Arc.Storage.S3.put/3
        (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

What have I missed.
Thanks

**Comment by Morganjackson** [comment]
@ckgagan did you find a solution to this error? 

I have the same `has_many :images, MyApp.Image` which works fine for a single image but I cant figure out how to upload multiple images. 

If I add ` multiple: true` to my file_input I get this:

`Request: POST /admin/posts
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Arc.Actions.Store.store/2
        lib/arc/actions/store.ex:8: Arc.Actions.Store.store(Ap.BlogPost, [%Plug.Upload{content_type: "image/png", filename: "nodejs-1920x1200.png", path: "/var/folders/3l/j0tny20n2qg0n5zd6rwx8whr0000gn/T//plug-1482/multipart-557305-982633-1"}, %Plug.Upload{content_type: "image/jpeg", filename: "photo-1461611034385-e082102d5c75.jpeg", path: "/var/folders/3l/j0tny20n2qg0n5zd6rwx8whr0000gn/T//plug-1482/multipart-557305-999697-1"}, %Plug.Upload{content_type: "image/jpeg", filename: "photo.JPG", path: "/var/folders/3l/j0tny20n2qg0n5zd6rwx8whr0000gn/T//plug-1482/multipart-557306-7062-1"}])`

**Comment by jethro-riosa** [comment]
` def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:url])
    |> set_delete_action()
    |> cast_attachments(params, [:id, :url])
  end`

you need to insert an id
